[tool.pytest.ini_options]
# Configuration for pytest
testpaths = ["backend/tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Asyncio configuration
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

# Logging configuration
log_cli = false
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

# Warnings configuration
filterwarnings = [
    "ignore::DeprecationWarning:chromadb.*",
    "ignore::langchain_core._api.deprecation.LangChainDeprecationWarning",
    "ignore::DeprecationWarning:langchain_community.*",
    "ignore::UserWarning:langchain_huggingface.*",
    "ignore::FutureWarning:langchain_chroma.*",
    "ignore::PendingDeprecationWarning:sentence_transformers.*",
]

# Test discovery
addopts = "-v --tb=short"
